# Generated by Django 4.0.6 on 2022-07-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
